version: '2.1'

services:
  app:
    image: docker-within
    build: ./another-way
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
